//
// Copyright(C) 1993-1996 Id Software, Inc.
// Copyright(C) 2005-2014 Simon Howard
//
// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU General Public License
// as published by the Free Software Foundation; either version 2
// of the License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
//
// DESCRIPTION: Event handling.
//
// Events are asynchronous inputs generally generated by the game user.
// Events can be discarded if no responder claims them
//

#include <stddef.h>
#include "doomdef.h"
#include "d_event.h"
//
// D_PostEvent
// Called by the I/O functions when input is detected
//
void D_PostEvent(doom_data_t *doom, event_t *ev)
{
    doom->events[doom->eventhead] = *ev;
    doom->eventhead = (doom->eventhead + 1) % MAXEVENTS;
}

// Read an event from the queue.

event_t *D_PopEvent(doom_data_t *doom)
{
    event_t *result;

    // No more events waiting.

    if (doom->eventtail == doom->eventhead)
    {
            return NULL;
    }

    result = &doom->events[doom->eventtail];

    // Advance to the next event in the queue.

    doom->eventtail = (doom->eventtail + 1) % MAXEVENTS;

    return result;
}
